require("redo.lazy")
require("redo.general")
require("redo.remap")
require("redo.treesitter")
require("redo.lsp")
require("redo.mason")
require("redo.cmp")
require("redo.telescope")
require("redo.obsidian")
require("redo.oil")
require("redo.metals")
require("redo.md")

os.execute('rm -r ~/.cache/jdtls')
